org: andreasonny83
service: rhythmic-excellence-registrations
useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  environment:
    STRIPED_SECRET_KEY: ${env:STRIPED_SECRET_KEY}

functions:
  webhook:
    handler: handler.webhook
    url:
      cors: false
