org: andreasonny83
app: rhythmic-excellence-mail-sender
service: rhythmic-excellence-mail-sender
configValidationMode: error

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  memorySize: 512
  timeout: 8
  stage: production
  versionFunctions: false
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'ses:SendEmail'
          Resource: '*'
  apiGateway:
    usagePlan: # Optional usage plan configuration
      quota:
        limit: 1000
        offset: 2
        period: MONTH
      throttle:
        burstLimit: 100
        rateLimit: 50

functions:
  send:
    handler: handler.send
    name: ${self:provider.stage}-rhythmicExcellenceMailsender
    description: Send emails coming from RhythmicExcellence website
    memorySize: 512
    timeout: 8
    events:
      - http:
          path: send
          method: post
          cors:
            origins:
              - 'https://www.rhythmicexcellence.london'
            headers:
              - Content-Type
              - X-Api-Key

package:
  patterns:
    - '!README.md'
    - '!LICENSE'
    - '!.prettierrc'
    - '!package-lock.json'
    - '!__tests__/**'
    - '!.env*'

plugins:
  - serverless-offline
